import json
import random
from datetime import datetime
from pathlib import Path

def generate_test_data():
    # 创建示例数据
    data = {
        "timestamp": datetime.now().isoformat(),
        "random_numbers": [random.randint(1, 100) for _ in range(5)],
        "test_message": "This is test data generated by GitHub Actions"
    }
    
    # 确保输出目录存在
    output_dir = Path("data")
    output_dir.mkdir(exist_ok=True)
    
    # 将数据写入文件
    output_file = output_dir / f"test_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(output_file, "w") as f:
        json.dump(data, f, indent=2)

if __name__ == "__main__":
    generate_test_data()
