name: Generate Test Data

on:
  # 允许手动触发工作流
  workflow_dispatch:
  # 也可以添加其他触发器，比如推送到main分支时
  # push:
  #   branches: [ main ]

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果有requirements.txt，取消下面的注释
        # pip install -r requirements.txt
        
    - name: Run Python script
      run: |
        python generate_data.py
        
    - name: Commit and push files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/
        git commit -m "Update test data file" -a
        git push
